-- PetMatch PostgreSQL schema for Supabase/Render deployments
-- Run this first in the Supabase SQL editor.

create table if not exists users (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  phone text,
  address text,
  created_at timestamptz,
  is_premium boolean not null default false,
  premium_since timestamptz,
  subscription jsonb not null default '{}'::jsonb,
  is_admin boolean not null default false,
  is_veterinarian boolean not null default false,
  is_verified_veterinarian boolean not null default false,
  veterinarian_details jsonb not null default '{}'::jsonb,
  coupons jsonb not null default '[]'::jsonb,
  rejected_requests jsonb not null default '[]'::jsonb,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists products (
  id integer generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(12, 2) not null default 0,
  category text,
  pet_type text,
  image text,
  stock integer not null default 0,
  exclusive boolean not null default false,
  is_on_sale boolean not null default false,
  sale_price numeric(12, 2),
  created_at timestamptz,
  updated_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists orders (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete set null,
  items jsonb not null default '[]'::jsonb,
  customer_info jsonb not null default '{}'::jsonb,
  total numeric(12, 2) not null default 0,
  items_total numeric(12, 2) not null default 0,
  shipping_cost numeric(12, 2) not null default 0,
  premium_discount numeric(12, 2) not null default 0,
  coupon_discount numeric(12, 2) not null default 0,
  coupon_code text,
  status text not null default 'pendiente',
  order_date timestamptz,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists invoices (
  id integer generated by default as identity primary key,
  invoice_number text not null unique,
  order_id integer,
  user_id integer references users(id) on delete set null,
  customer_name text,
  customer_email text,
  items jsonb not null default '[]'::jsonb,
  items_total numeric(12, 2) not null default 0,
  shipping_cost numeric(12, 2) not null default 0,
  premium_discount numeric(12, 2) not null default 0,
  coupon_discount numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  status text not null default 'emitida',
  issued_at timestamptz,
  payment_method text,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists pets (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete cascade,
  name text not null,
  type text,
  breed text,
  birth_date date,
  gender text,
  weight numeric(8, 2),
  photo text,
  medical_info jsonb not null default '{}'::jsonb,
  preferences jsonb not null default '{}'::jsonb,
  activity_level text,
  special_needs text,
  created_at timestamptz,
  updated_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists consultations (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete set null,
  user_name text,
  title text not null,
  question text not null,
  pet_type text,
  pet_id integer references pets(id) on delete set null,
  pet_name text,
  pet_photo text,
  created_at timestamptz,
  status text not null default 'pending',
  answer text,
  answered_at timestamptz,
  answered_by text,
  answered_by_type text,
  answered_by_user_id integer references users(id) on delete set null,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists reviews (
  id integer generated by default as identity primary key,
  product_id integer references products(id) on delete cascade,
  user_id integer references users(id) on delete set null,
  user_name text,
  rating integer not null check (rating between 1 and 5),
  comment text,
  review_date timestamptz,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists veterinarian_requests (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete set null,
  user_name text,
  user_email text,
  professional_license text,
  license_number text,
  clinic text,
  specialties text,
  certificate_path text,
  certificate_file_name text,
  submitted_at timestamptz,
  status text not null default 'pending',
  reviewed_at timestamptz,
  reviewed_by integer references users(id) on delete set null,
  rejected_at timestamptz,
  rejection_reason text,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists coupons (
  id bigserial primary key,
  code text unique,
  type text,
  discount_percent numeric(5, 2),
  issued_at timestamptz,
  month_key text,
  redeemed boolean not null default false,
  used_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists site_content (
  id text primary key default 'main',
  content jsonb not null,
  updated_at timestamptz
);

create index if not exists idx_products_category on products(category);
create index if not exists idx_products_pet_type on products(pet_type);
create index if not exists idx_orders_user_id on orders(user_id);
create index if not exists idx_invoices_user_id on invoices(user_id);
create index if not exists idx_pets_user_id on pets(user_id);
create index if not exists idx_consultations_user_id on consultations(user_id);
create index if not exists idx_reviews_product_id on reviews(product_id);
